import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  gettingStarted: [
    {
      type: 'doc',
      id: 'getting-started/introduction',
      label: 'Introduction',
    },
    {
      type: 'doc',
      id: 'user/getting-started',
      label: 'Quick Start Guide',
    },
    {
      type: 'doc',
      id: 'development/guide',
      label: 'Development Guide',
    },
    {
      type: 'doc',
      id: 'deployment/guide',
      label: 'Deployment',
    },
  ],
  
  user: [
    {
      type: 'doc',
      id: 'user/capturing-conversations',
      label: 'Capturing Conversations',
    },
    {
      type: 'doc',
      id: 'user/searching-finding',
      label: 'Searching & Finding',
    },
    {
      type: 'doc',
      id: 'user/collections',
      label: 'Collections',
    },
    {
      type: 'doc',
      id: 'user/bookmarks',
      label: 'Bookmarks',
    },
    {
      type: 'doc',
      id: 'user/for-you',
      label: 'For You Recommendations',
    },
    {
      type: 'doc',
      id: 'user/ai-chat',
      label: 'AI Chat',
    },
    {
      type: 'doc',
      id: 'user/byok-chat',
      label: 'BYOK Chat',
    },
    {
      type: 'doc',
      id: 'user/sharing',
      label: 'Sharing Knowledge',
    },
    {
      type: 'doc',
      id: 'user/context-recipes',
      label: 'Context Recipes',
    },
    {
      type: 'doc',
      id: 'user/context-cockpit',
      label: 'Context Cockpit',
    },
    {
      type: 'doc',
      id: 'user/context-components',
      label: 'Context Components (ACUs)',
    },
    {
      type: 'doc',
      id: 'user/analytics',
      label: 'Analytics',
    },
    {
      type: 'doc',
      id: 'user/error-dashboard',
      label: 'Error Dashboard',
    },
    {
      type: 'doc',
      id: 'user/settings-account',
      label: 'Settings & Account',
    },
  ],
  
  architecture: [
    {
      type: 'doc',
      id: 'architecture/overview',
      label: 'Overview',
    },
    {
      type: 'autogenerated',
      dirName: 'architecture',
    },
  ],
  
  api: [
    {
      type: 'doc',
      id: 'api/overview',
      label: 'REST API',
    },
  ],
  
  pwa: [
    {
      type: 'doc',
      id: 'pwa/overview',
      label: 'PWA Overview',
    },
    {
      type: 'doc',
      id: 'pwa/byok',
      label: 'BYOK',
    },
    {
      type: 'doc',
      id: 'pwa/storage-v2',
      label: 'Storage V2',
    },
    {
      type: 'doc',
      id: 'pwa/content-renderer',
      label: 'Content Renderer',
    },
  ],
  
  network: [
    {
      type: 'doc',
      id: 'network/overview',
      label: 'Network Overview',
    },
    {
      type: 'doc',
      id: 'network/security',
      label: 'Security',
    },
  ],
  
  database: [
    {
      type: 'doc',
      id: 'database/schema',
      label: 'Schema',
    },
  ],
  
  social: [
    {
      type: 'doc',
      id: 'social/overview',
      label: 'Social Features',
    },
  ],
  
  admin: [
    {
      type: 'doc',
      id: 'admin/overview',
      label: 'Admin Panel',
    },
  ],
  
  security: [
    {
      type: 'doc',
      id: 'security/overview',
      label: 'Security Overview',
    },
  ],
  
  common: [
    {
      type: 'doc',
      id: 'common/overview',
      label: 'Common Utils',
    },
  ],
  
  reference: [
    {
      type: 'doc',
      id: 'reference/types',
      label: 'TypeScript Types',
    },
  ],
};

export default sidebars;
