import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  gettingStarted: [
    {
      type: 'doc',
      id: 'getting-started/introduction',
      label: 'Introduction',
    },
    {
      type: 'doc',
      id: 'development/guide',
      label: 'Development Guide',
    },
    {
      type: 'doc',
      id: 'deployment/guide',
      label: 'Deployment',
    },
  ],
  
  architecture: [
    {
      type: 'doc',
      id: 'architecture/overview',
      label: 'Overview',
    },
    {
      type: 'autogenerated',
      dirName: 'architecture',
    },
  ],
  
  api: [
    {
      type: 'doc',
      id: 'api/overview',
      label: 'REST API',
    },
  ],
  
  pwa: [
    {
      type: 'doc',
      id: 'pwa/overview',
      label: 'PWA Overview',
    },
    {
      type: 'doc',
      id: 'pwa/byok',
      label: 'BYOK',
    },
    {
      type: 'doc',
      id: 'pwa/storage-v2',
      label: 'Storage V2',
    },
    {
      type: 'doc',
      id: 'pwa/content-renderer',
      label: 'Content Renderer',
    },
  ],
  
  network: [
    {
      type: 'doc',
      id: 'network/overview',
      label: 'Network Overview',
    },
    {
      type: 'doc',
      id: 'network/security',
      label: 'Security',
    },
  ],
  
  database: [
    {
      type: 'doc',
      id: 'database/schema',
      label: 'Schema',
    },
  ],
  
  social: [
    {
      type: 'doc',
      id: 'social/overview',
      label: 'Social Features',
    },
  ],
  
  admin: [
    {
      type: 'doc',
      id: 'admin/overview',
      label: 'Admin Panel',
    },
  ],
  
  security: [
    {
      type: 'doc',
      id: 'security/overview',
      label: 'Security Overview',
    },
  ],
  
  common: [
    {
      type: 'doc',
      id: 'common/overview',
      label: 'Common Utils',
    },
  ],
  
  reference: [
    {
      type: 'doc',
      id: 'reference/types',
      label: 'TypeScript Types',
    },
  ],
};

export default sidebars;
